import { chromium } from 'playwright';
import { CHROMIUM, openApp } from './testlib.mjs';
const b=await chromium.launch({executablePath:CHROMIUM});
const p=await b.newPage({viewport:{width:1400,height:900}});
await openApp(p);
await p.evaluate(()=>{ S.items=[]; S.sel=null; commit(); showHome(); }); await p.waitForTimeout(400);
await p.click('#homeBrands'); await p.waitForTimeout(1000);
await p.screenshot({path:'/tmp/b-list.png'});
await p.locator('#brandWrap .bcard').nth(3).click(); await p.waitForTimeout(1200);
await p.screenshot({path:'/tmp/b-edit.png'});
await b.close(); console.log('ok');
