import { chromium } from 'playwright';
import { CHROMIUM, openApp, resetDb, testPhoto } from './testlib.mjs';
resetDb();
const b=await chromium.launch({executablePath:CHROMIUM});
const shot=async(p,name)=>{ await p.screenshot({path:'/tmp/ux-'+name+'.png'}); };
const p=await b.newPage({viewport:{width:1400,height:900}});
p.on('filechooser',async fc=>{try{await fc.setFiles([])}catch(e){}});
await openApp(p);
await shot(p,'01-home');
await p.click('#homeNew'); await p.waitForTimeout(350); await shot(p,'02-photoask');
await p.click('#startPhoto'); await p.waitForTimeout(500);
await p.evaluate(()=>showPanel('text')); await p.waitForTimeout(300); await shot(p,'03-words');
await p.evaluate(()=>showPanel('layout')); await p.waitForTimeout(300); await shot(p,'04-layout-photo');
await p.evaluate(()=>{S.items=[];S.sel=null;startGraphic(false);}); await p.waitForTimeout(400);
await p.evaluate(()=>showPanel('layout')); await p.waitForTimeout(300); await shot(p,'05-layout-type');
await p.evaluate(()=>{S.items=[];S.sel=null;startGraphic(true);}); await p.waitForTimeout(400);
await p.evaluate(()=>showPanel('photo')); await p.waitForTimeout(300); await shot(p,'06-photo-empty');
const ch=await Promise.all([p.waitForEvent('filechooser'),p.click('#drop')]).then(r=>r[0]);
await ch.setFiles(testPhoto()); await p.waitForTimeout(2600); await shot(p,'07-photo-loaded');
await p.evaluate(()=>showPanel('library')); await p.waitForTimeout(300); await shot(p,'08-library-panel');
await p.evaluate(()=>showPanel('export')); await p.waitForTimeout(300); await shot(p,'09-export');
await p.evaluate(()=>showPanel('sizes')); await p.waitForTimeout(300); await shot(p,'10-sizes');
await b.close();
const m=await chromium.launch({executablePath:CHROMIUM});
const q=await m.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
await openApp(q);
await shot(q,'20-phone-home');
await q.click('#homeNew'); await q.waitForTimeout(350); await shot(q,'21-phone-ask');
await q.click('#startPhoto'); await q.waitForTimeout(500);
await q.evaluate(()=>showPanel('layout')); await q.waitForTimeout(350); await shot(q,'22-phone-layout');
await q.evaluate(()=>showPanel('photo')); await q.waitForTimeout(350); await shot(q,'23-phone-photo');
await m.close();
console.log('shots written');
