import { chromium } from 'playwright';
import { CHROMIUM, openApp, resetDb, testPhoto } from './testlib.mjs';
resetDb();
const b=await chromium.launch({executablePath:CHROMIUM});
const p=await b.newPage({viewport:{width:1400,height:900}});
p.on('filechooser',async fc=>{try{await fc.setFiles([])}catch(e){}});
await openApp(p);
await p.screenshot({path:'/tmp/v2-home.png'});
await p.evaluate(()=>startGraphic(true)); await p.waitForTimeout(500);
await p.evaluate(()=>showPanel('layout')); await p.waitForTimeout(350);
await p.screenshot({path:'/tmp/v2-layout.png'});
await b.close();
const m=await chromium.launch({executablePath:CHROMIUM});
const q=await m.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
q.on('filechooser',async fc=>{try{await fc.setFiles([])}catch(e){}});
await openApp(q);
await q.evaluate(()=>{ S.items=[]; S.sel=null; commit(); showHome(); }); await q.waitForTimeout(400);
await q.screenshot({path:'/tmp/v2-phone-home.png'});
await q.evaluate(()=>startGraphic(false)); await q.waitForTimeout(500);
await q.evaluate(()=>showPanel('layout')); await q.waitForTimeout(400);
await q.screenshot({path:'/tmp/v2-phone-layout.png'});
await m.close();
console.log('ok');
