import { chromium } from 'playwright';
import { CHROMIUM, openApp, resetDb, testPhoto } from './testlib.mjs';
resetDb();
const b=await chromium.launch({executablePath:CHROMIUM});
const p=await b.newPage({viewport:{width:1400,height:900}});
p.on('filechooser',async fc=>{try{await fc.setFiles([])}catch(e){}});
await openApp(p);
// build two saved graphics
await p.evaluate(()=>startGraphic(true)); await p.waitForTimeout(400);
await p.evaluate(()=>showPanel('photo')); await p.waitForTimeout(250);
const ch=await Promise.all([p.waitForEvent('filechooser'),p.click('#drop')]).then(r=>r[0]);
await ch.setFiles(testPhoto()); await p.waitForTimeout(2600);
await p.evaluate(()=>showPanel('library')); await p.waitForTimeout(250);
await p.screenshot({path:'/tmp/v3-libpanel.png'});
await p.evaluate(async()=>{
  const c=await (await api('/api/collections',{method:'POST',...asJson({name:'See It, Log It'})})).json();
  COLLECTIONS.push({...c,count:0}); fillCollections(); document.getElementById('fCollection').value=c.id;
});
await p.click('#btnSaveLib');
await p.waitForFunction(()=>/Saved\.|ould not/.test(document.getElementById('libStatus').textContent),null,{timeout:90000});
await p.waitForTimeout(1600);
await p.screenshot({path:'/tmp/v3-lib-collection.png'});
await p.locator('#libWrap .gcard').first().click(); await p.waitForTimeout(800);
await p.screenshot({path:'/tmp/v3-lib-graphic.png'});
await p.click('#libBack'); await p.waitForTimeout(400);
await p.click('#libSelect'); await p.waitForTimeout(250);
await p.locator('#libWrap .gcard').first().click(); await p.waitForTimeout(250);
await p.click('#libDownloadSel'); await p.waitForTimeout(600);
await p.screenshot({path:'/tmp/v3-platforms.png'});
await p.evaluate(()=>document.getElementById('dlgPlatforms').close());
await p.click('#libBack').catch(()=>{});
await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/v3-lib-home.png'});
await b.close(); console.log('ok');
